-- =============================================================================
-- TISCHTENNIS-SCHEMA (neue Tabellen, gleiches Supabase-Projekt)
-- Voraussetzung: discovery.sql wurde ausgefuehrt und die RLS-Policies der
-- bestehenden Tabellen (z.B. "Tables") gesichtet.
--
-- WICHTIG zu RLS: Das Frontend nutzt den Anon-Key direkt. Die Policies unten
-- erlauben dem Anon-Rollen vollen CRUD-Zugriff (true/true) — das spiegelt das
-- bisherige Verhalten der App. Falls discovery.sql zeigt, dass die bestehenden
-- Tabellen restriktivere Policies haben, diese hier entsprechend anpassen.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- Tabellen
-- ---------------------------------------------------------------------------
create table if not exists public.tt_matches (
  id                  bigint generated by default as identity primary key,
  created_at          timestamptz not null default now(),
  name                text,
  format              text not null check (format in ('singles','doubles')),
  best_of             int  not null default 3 check (best_of >= 1),
  is_open             boolean not null default true,
  exclude_from_overall boolean not null default false
);

create table if not exists public.tt_match_players (
  match_id  bigint not null references public.tt_matches(id) on delete cascade,
  player_id bigint not null references public."Players"(id) on delete cascade,
  side      text   not null check (side in ('A','B')),
  primary key (match_id, player_id)
);

create table if not exists public.tt_sets (
  id          bigint generated by default as identity primary key,
  match_id    bigint not null references public.tt_matches(id) on delete cascade,
  set_number  int    not null,
  score_a     int    not null default 0,
  score_b     int    not null default 0,
  created_at  timestamptz not null default now(),
  unique (match_id, set_number)
);

create index if not exists tt_match_players_match_idx on public.tt_match_players(match_id);
create index if not exists tt_match_players_player_idx on public.tt_match_players(player_id);
create index if not exists tt_sets_match_idx on public.tt_sets(match_id);

-- ---------------------------------------------------------------------------
-- Row Level Security
-- Exakt gespiegelt von den bestehenden Tabellen (Players/Tables/round_scores):
--   SELECT -> public, using (true)
--   INSERT -> anon,   with check (true)
--   UPDATE -> anon,   using (true) with check (true)
-- Kein DELETE (die App loescht keine Zeilen).
-- ---------------------------------------------------------------------------
alter table public.tt_matches        enable row level security;
alter table public.tt_match_players  enable row level security;
alter table public.tt_sets           enable row level security;

-- tt_matches
create policy "Enable read access for all users" on public.tt_matches
  for select to public using (true);
create policy "Enable insert for all users" on public.tt_matches
  for insert to anon with check (true);
create policy "Enable update for all" on public.tt_matches
  for update to anon using (true) with check (true);

-- tt_match_players
create policy "Enable read access for all users" on public.tt_match_players
  for select to public using (true);
create policy "Enable insert for all users" on public.tt_match_players
  for insert to anon with check (true);
create policy "Enable update for all" on public.tt_match_players
  for update to anon using (true) with check (true);

-- tt_sets
create policy "Enable read access for all users" on public.tt_sets
  for select to public using (true);
create policy "Enable insert for all users" on public.tt_sets
  for insert to anon with check (true);
create policy "Enable update for all" on public.tt_sets
  for update to anon using (true) with check (true);

-- ---------------------------------------------------------------------------
-- Realtime (optional): Tabellen zur supabase_realtime-Publication hinzufuegen,
-- falls Live-Updates in TTMatchDetails gewuenscht sind.
-- ---------------------------------------------------------------------------
-- alter publication supabase_realtime add table public.tt_matches;
-- alter publication supabase_realtime add table public.tt_match_players;
-- alter publication supabase_realtime add table public.tt_sets;
